export const data = [
  {
    event: "ALMERIA - ALBACETE",
    date: "15/12/2024 21:45",
    predictability: "HIGH",
    odds: [
      {
        label: "Almeria",
        back: 1.79,
        adjustBack: 1.74,
        lay: 1.8,
        adjustLay: 1.94,
        probability: 43.04,
        backValue: -25.17,
      },
      {
        label: "Albacete",
        back: 4.9,
        adjustBack: 4.65,
        lay: 5.0,
        adjustLay: 1.94,
        probability: 28.51,
        backValue: 32.47,
      },
      {
        label: "Draw",
        back: 4.1,
        adjustBack: 3.9,
        lay: 4.3,
        adjustLay: 1.94,
        probability: 28.45,
        backValue: 10.91,
      },
    ],
    sections: [
      { title: "Match Odds", predictability: "HIGH" },
      { title: "Under Over 1.5" },
      { title: "Under Over 2.5" },
      { title: "Under Over 3.5" },
      { title: "BTTS" },
      { title: "Correct Score" },
    ],
  },
  {
    event: "ELFSBORG - OSASUNA",
    date: "15/12/2024 21:45",
    predictability: "HIGH",
    odds: [
      {
        label: "Almeria",
        back: 1.79,
        adjustBack: 1.74,
        lay: 1.8,
        adjustLay: 1.94,
        probability: 43.04,
        backValue: -25.17,
      },
      {
        label: "Albacete",
        back: 4.9,
        adjustBack: 4.65,
        lay: 5.0,
        adjustLay: 1.94,
        probability: 28.51,
        backValue: 32.47,
      },
      {
        label: "Draw",
        back: 4.1,
        adjustBack: 3.9,
        lay: 4.3,
        adjustLay: 1.94,
        probability: 28.45,
        backValue: 10.91,
      },
    ],
    sections: [{ title: "Match Odds", predictability: "HIGH" }],
  },
];
