export const tableData = [
  {
    headerName: "ALMERIA - ALBACETE",
    bettings: [
      {
        bettingCategory: "Match Odds",
        odd: [
          {
            event: "Albacete",
            predictability: "HIGH",
            back: 11.5,
            backOther: 10.82,
            adjustBack: 10.46,
            lay: 12.0,
            adjustLay: 1.94,
            probability: 14.73,
            realBack: 6.789,
            realLay: 1.173,
            backValue: "54.11%",
            layValue: "-43.43%",
            kFactorBack: "5.72%",
            kFactorLay: "-6.84%",
            backAmount: 1.42,
            layAmount: 0.0,
            placedBet: 0.0,
          },
          {
            event: "Draw",
            predictability: "HIGH",
            back: 6.0,
            backOther: 5.68,
            adjustBack: 5.49,
            lay: 6.2,
            adjustLay: 1.94,
            probability: 21.61,
            realBack: 4.627,
            realLay: 1.276,
            backValue: "18.61%",
            layValue: "-23.36%",
            kFactorBack: "4.11%",
            kFactorLay: "-3.86%",
            backAmount: 1.03,
            layAmount: 0.0,
            placedBet: 0.0,
          },
        ],
      },
      {
        bettingCategory: "Under Over 1.5",
        odd: [
          {
            event: "Albacete",
            predictability: "HIGH",
            back: 11.5,
            backOther: 10.82,
            adjustBack: 10.46,
            lay: 12.0,
            adjustLay: 1.94,
            probability: 14.73,
            realBack: 6.789,
            realLay: 1.173,
            backValue: "54.11%",
            layValue: "-43.43%",
            kFactorBack: "5.72%",
            kFactorLay: "-6.84%",
            backAmount: 1.42,
            layAmount: 0.0,
            placedBet: 0.0,
          },
          {
            event: "Draw",
            predictability: "HIGH",
            back: 6.0,
            backOther: 5.68,
            adjustBack: 5.49,
            lay: 6.2,
            adjustLay: 1.94,
            probability: 21.61,
            realBack: 4.627,
            realLay: 1.276,
            backValue: "18.61%",
            layValue: "-23.36%",
            kFactorBack: "4.11%",
            kFactorLay: "-3.86%",
            backAmount: 1.03,
            layAmount: 0.0,
            placedBet: 0.0,
          },
        ],
      },
      {
        bettingCategory: "Under Over 2.5",
        odd: [
          {
            event: "Albacete",
            predictability: "HIGH",
            back: 11.5,
            backOther: 10.82,
            adjustBack: 10.46,
            lay: 12.0,
            adjustLay: 1.94,
            probability: 14.73,
            realBack: 6.789,
            realLay: 1.173,
            backValue: "54.11%",
            layValue: "-43.43%",
            kFactorBack: "5.72%",
            kFactorLay: "-6.84%",
            backAmount: 1.42,
            layAmount: 0.0,
            placedBet: 0.0,
          },
          {
            event: "Draw",
            predictability: "HIGH",
            back: 6.0,
            backOther: 5.68,
            adjustBack: 5.49,
            lay: 6.2,
            adjustLay: 1.94,
            probability: 21.61,
            realBack: 4.627,
            realLay: 1.276,
            backValue: "18.61%",
            layValue: "-23.36%",
            kFactorBack: "4.11%",
            kFactorLay: "-3.86%",
            backAmount: 1.03,
            layAmount: 0.0,
            placedBet: 0.0,
          },
        ],
      },
      {
        bettingCategory: "Under Over 3.5",
        odd: [
          {
            event: "Albacete",
            predictability: "HIGH",
            back: 11.5,
            backOther: 10.82,
            adjustBack: 10.46,
            lay: 12.0,
            adjustLay: 1.94,
            probability: 14.73,
            realBack: 6.789,
            realLay: 1.173,
            backValue: "54.11%",
            layValue: "-43.43%",
            kFactorBack: "5.72%",
            kFactorLay: "-6.84%",
            backAmount: 1.42,
            layAmount: 0.0,
            placedBet: 0.0,
          },
          {
            event: "Draw",
            predictability: "HIGH",
            back: 6.0,
            backOther: 5.68,
            adjustBack: 5.49,
            lay: 6.2,
            adjustLay: 1.94,
            probability: 21.61,
            realBack: 4.627,
            realLay: 1.276,
            backValue: "18.61%",
            layValue: "-23.36%",
            kFactorBack: "4.11%",
            kFactorLay: "-3.86%",
            backAmount: 1.03,
            layAmount: 0.0,
            placedBet: 0.0,
          },
        ],
      },
      {
        bettingCategory: "BTTS",
        odd: [
          {
            event: "Albacete",
            predictability: "HIGH",
            back: 11.5,
            backOther: 10.82,
            adjustBack: 10.46,
            lay: 12.0,
            adjustLay: 1.94,
            probability: 14.73,
            realBack: 6.789,
            realLay: 1.173,
            backValue: "54.11%",
            layValue: "-43.43%",
            kFactorBack: "5.72%",
            kFactorLay: "-6.84%",
            backAmount: 1.42,
            layAmount: 0.0,
            placedBet: 0.0,
          },
          {
            event: "Draw",
            predictability: "HIGH",
            back: 6.0,
            backOther: 5.68,
            adjustBack: 5.49,
            lay: 6.2,
            adjustLay: 1.94,
            probability: 21.61,
            realBack: 4.627,
            realLay: 1.276,
            backValue: "18.61%",
            layValue: "-23.36%",
            kFactorBack: "4.11%",
            kFactorLay: "-3.86%",
            backAmount: 1.03,
            layAmount: 0.0,
            placedBet: 0.0,
          },
        ],
      },
      {
        bettingCategory: "Correct Score",
        odd: [
          {
            event: "Albacete",
            predictability: "HIGH",
            back: 11.5,
            backOther: 10.82,
            adjustBack: 10.46,
            lay: 12.0,
            adjustLay: 1.94,
            probability: 14.73,
            realBack: 6.789,
            realLay: 1.173,
            backValue: "54.11%",
            layValue: "-43.43%",
            kFactorBack: "5.72%",
            kFactorLay: "-6.84%",
            backAmount: 1.42,
            layAmount: 0.0,
            placedBet: 0.0,
          },
          {
            event: "Draw",
            predictability: "HIGH",
            back: 6.0,
            backOther: 5.68,
            adjustBack: 5.49,
            lay: 6.2,
            adjustLay: 1.94,
            probability: 21.61,
            realBack: 4.627,
            realLay: 1.276,
            backValue: "18.61%",
            layValue: "-23.36%",
            kFactorBack: "4.11%",
            kFactorLay: "-3.86%",
            backAmount: 1.03,
            layAmount: 0.0,
            placedBet: 0.0,
          },
        ],
      },
    ],
  },
  {
    headerName: "ELFSBORG - OSASUNA",
    bettings: [
      {
        bettingCategory: "Match Odds",
        odd: [
          {
            event: "Albacete",
            predictability: "HIGH",
            back: 11.5,
            backOther: 10.82,
            adjustBack: 10.46,
            lay: 12.0,
            adjustLay: 1.94,
            probability: 14.73,
            realBack: 6.789,
            realLay: 1.173,
            backValue: "54.11%",
            layValue: "-43.43%",
            kFactorBack: "5.72%",
            kFactorLay: "-6.84%",
            backAmount: 1.42,
            layAmount: 0.0,
            placedBet: 0.0,
          },
          {
            event: "Draw",
            predictability: "HIGH",
            back: 6.0,
            backOther: 5.68,
            adjustBack: 5.49,
            lay: 6.2,
            adjustLay: 1.94,
            probability: 21.61,
            realBack: 4.627,
            realLay: 1.276,
            backValue: "18.61%",
            layValue: "-23.36%",
            kFactorBack: "4.11%",
            kFactorLay: "-3.86%",
            backAmount: 1.03,
            layAmount: 0.0,
            placedBet: 0.0,
          },
        ],
      },
    ],
  },
];
